// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5u7G4TnC2CoksVRkcbAXfz3JcA8U66Eg',
    appId: '1:924539906728:web:cd8235efd821501ba7309d',
    messagingSenderId: '924539906728',
    projectId: 'apps-99a59',
    authDomain: 'apps-99a59.firebaseapp.com',
    storageBucket: 'apps-99a59.firebasestorage.app',
    measurementId: 'G-PW3012NFSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGCiC_xbYZAmu5AjTEuvZQRVrk09jH8xg',
    appId: '1:782157691994:android:6b4f179438e58b10996c63',
    messagingSenderId: '782157691994',
    projectId: 'fir-options-a09b9',
    storageBucket: 'fir-options-a09b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGROWHpzZj2ztk9mBgtIRSG2tMV8LjUc',
    appId: '1:782157691994:ios:52691a8ab9590943996c63',
    messagingSenderId: '782157691994',
    projectId: 'fir-options-a09b9',
    storageBucket: 'fir-options-a09b9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQGROWHpzZj2ztk9mBgtIRSG2tMV8LjUc',
    appId: '1:782157691994:ios:52691a8ab9590943996c63',
    messagingSenderId: '782157691994',
    projectId: 'fir-options-a09b9',
    storageBucket: 'fir-options-a09b9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
