// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5u7G4TnC2CoksVRkcbAXfz3JcA8U66Eg',
    appId: '1:924539906728:web:cd8235efd821501ba7309d',
    messagingSenderId: '924539906728',
    projectId: 'apps-99a59',
    authDomain: 'apps-99a59.firebaseapp.com',
    storageBucket: 'apps-99a59.firebasestorage.app',
    measurementId: 'G-PW3012NFSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqH5lF0KzcmrXRQb9VziTMdTL5a2SSVZE',
    appId: '1:924539906728:android:40008b5d772bfc6da7309d',
    messagingSenderId: '924539906728',
    projectId: 'apps-99a59',
    storageBucket: 'apps-99a59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeYjixdjmCILj7Sq1nL-PYFQN6OmrEBJc',
    appId: '1:924539906728:ios:eacba26f1a36a0a5a7309d',
    messagingSenderId: '924539906728',
    projectId: 'apps-99a59',
    storageBucket: 'apps-99a59.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeYjixdjmCILj7Sq1nL-PYFQN6OmrEBJc',
    appId: '1:924539906728:ios:eacba26f1a36a0a5a7309d',
    messagingSenderId: '924539906728',
    projectId: 'apps-99a59',
    storageBucket: 'apps-99a59.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5u7G4TnC2CoksVRkcbAXfz3JcA8U66Eg',
    appId: '1:924539906728:web:ceda4bd7da208b36a7309d',
    messagingSenderId: '924539906728',
    projectId: 'apps-99a59',
    authDomain: 'apps-99a59.firebaseapp.com',
    storageBucket: 'apps-99a59.firebasestorage.app',
    measurementId: 'G-X9SZY4SVN0',
  );
}
